GET http://127.0.0.1:8000/api/v1/customers


###
POST http://127.0.0.1:8000/api/v1/create-user/
Content-Type: application/json

{"email": "paul@email.com", "password": "example123#", "first_name": "Paul", "last_name": "David"}


###
POST http://127.0.0.1:8000/api/v1/login/
Content-Type: application/json

{"email": "paul@email.com", "password": "example123#"}


###
GET http://127.0.0.1:8000/api/v1/organisations
Authorization: Token 120ee175e7cba45cf6884c321ce807e04d148ffd

