# Generated by Django 4.2.11 on 2024-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transaction_created_at_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prev_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
