# Generated by Django 5.0.6 on 2024-05-13 23:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_organisation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
