# Generated by Django 4.2.11 on 2024-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transaction_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='prev_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
            preserve_default=False,
        ),
    ]
