# Generated by Django 5.1.1 on 2024-10-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_organisation_total_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_of_payment',
            new_name='date_of_transaction',
        ),
    ]
