# Generated by Django 5.1.1 on 2024-10-14 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_date_of_payment_transaction_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
