# Generated by Django 4.2.11 on 2024-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_transaction_prev_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
