# Generated by Django 4.2.7 on 2024-05-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_organisation_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
